# Generated by Django 5.0 on 2023-12-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
