# Generated by Django 5.0 on 2023-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0003_alter_comentario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=255),
        ),
    ]
