# Generated by Django 5.0 on 2023-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_alter_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
