# Generated by Django 5.0 on 2024-01-02 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_profile_bio_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_postagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
